### ISSUE TITLE
Issue to use this project

### ISSUE THREAD

**Issue by Playstoreman** [PavlezT/alienbot#1]
What version of chrome i'm supposed to use and how do i run it ?

**Comment by PavlezT** [comment]
version of chrome? I guess you should have it already installed.
then, you should visit this page
> // download chrome from here http://chromedriver.storage.googleapis.com/index.html

and download appropriate `chromedriver` version, same as your installed Chrome browser.
Additionally, you should have **Node.js** installed (> 10 version).

Then, you should copy your cookies, from `all-access.wax.io` in JSON format. You can use `EditThisCookie` chrome extension. Insert that data as *1.json* file in *cookies* folder.

Run `chromedriver` (double click on downloaded file)
Run project by running command in terminal (cmd for Windows) `npm start`
(Only first time, you should run `npm install` before start)
